const nodemailer = require("nodemailer");

const EMAIL_HOST = process.env.EMAIL_HOST || "smtp.gmail.com";
const EMAIL_PORT = Number(process.env.EMAIL_PORT) || 465;
const EMAIL_USER = process.env.EMAIL_USER;
const EMAIL_PASS = process.env.EMAIL_PASS;
const EMAIL_SECURE =
  typeof process.env.EMAIL_SECURE === "string"
    ? process.env.EMAIL_SECURE.toLowerCase() === "true"
    : EMAIL_PORT === 465;
const SMTP_TIMEOUT = Number(process.env.SMTP_TIMEOUT_MS) || 5000;
const FALLBACK_FROM =
  process.env.EMAIL_FROM ||
  (EMAIL_USER
    ? `Smart Farmer <${EMAIL_USER}>`
    : "Smart Farmer <no-reply@smartfarmer.dev>");

const hasSmtpCredentials = EMAIL_HOST && EMAIL_PORT && EMAIL_USER && EMAIL_PASS;

let cachedEtherealAccount = null;

const createSmtpTransport = () => {
  return nodemailer.createTransport({
    host: EMAIL_HOST,
    port: EMAIL_PORT,
    secure: EMAIL_SECURE,
    connectionTimeout: SMTP_TIMEOUT,
    greetingTimeout: SMTP_TIMEOUT,
    socketTimeout: SMTP_TIMEOUT,
    auth: {
      user: EMAIL_USER,
      pass: EMAIL_PASS,
    },
  });
};

const createEtherealTransport = async () => {
  if (!cachedEtherealAccount) {
    cachedEtherealAccount = await nodemailer.createTestAccount();
    console.warn(
      "Using autogenerated Ethereal SMTP credentials for email delivery (development-only)."
    );
    console.warn(`Ethereal user: ${cachedEtherealAccount.user}`);
  }

  return nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false,
    auth: {
      user: cachedEtherealAccount.user,
      pass: cachedEtherealAccount.pass,
    },
  });
};

const createTransport = async () => {
  if (hasSmtpCredentials) {
    return createSmtpTransport();
  }

  return createEtherealTransport();
};

const isConnectionError = (error) =>
  error &&
  (error.code === "ETIMEDOUT" ||
    error.code === "ECONNREFUSED" ||
    error.code === "ECONNRESET" ||
    error.command === "CONN");

const sendEmail = async ({ to, subject, html, from }) => {
  try {
    const transport = await createTransport();
    const resolvedFrom =
      from ||
      (transport.options?.auth?.user
        ? `Smart Farmer <${transport.options.auth.user}>`
        : FALLBACK_FROM);
    try {
      const info = await transport.sendMail({
        from: resolvedFrom,
        to,
        subject,
        html,
      });
      if (transport.options?.host === "smtp.ethereal.email") {
        const previewUrl = nodemailer.getTestMessageUrl(info);
        if (previewUrl) {
          console.warn("Email delivered via Ethereal. Preview at:", previewUrl);
        }
      }
      return { success: true };
    } catch (primaryError) {
      if (
        !isConnectionError(primaryError) ||
        transport.options?.host === "smtp.ethereal.email"
      ) {
        throw primaryError;
      }

      console.warn(
        `[emailService] Primary transport failed (${primaryError.code}). Falling back to Ethereal.`
      );
      const fallbackTransport = await createEtherealTransport();
      const fallbackInfo = await fallbackTransport.sendMail({
        from: FALLBACK_FROM,
        to,
        subject,
        html,
      });
      const previewUrl = nodemailer.getTestMessageUrl(fallbackInfo);
      if (previewUrl) {
        console.warn(
          "Email delivered via Ethereal fallback. Preview at:",
          previewUrl
        );
      }
      return { success: true, fallback: true };
    }
  } catch (error) {
    console.error("Email send error:", error);
    throw error;
  }
};

const sendOtpEmail = async ({ email, otp, name }) => {
  const html = `<p>Hello${name ? ` ${name}` : ""},</p>
    <p>Your OTP for Smart Farmer is: <strong>${otp}</strong></p>
    <p>This code is valid for 10 minutes.</p>`;

  return sendEmail({
    to: email,
    subject: "Your Smart Farmer OTP",
    html,
  });
};

const sendPasswordResetEmail = async ({ email, name, resetUrl }) => {
  const html = `<p>Hello${name ? ` ${name}` : ""},</p>
    <p>Click <a href="${resetUrl}">here</a> to reset your password. This link is valid for 1 hour.</p>`;

  return sendEmail({
    to: email,
    subject: "Reset Your Smart Farmer Password",
    html,
  });
};

module.exports = {
  sendEmail,
  sendOtpEmail,
  sendPasswordResetEmail,
};
