const nodemailer = require("nodemailer");

const booleanFromEnv = (value, fallback = false) => {
  if (typeof value === "undefined") return fallback;
  if (typeof value === "boolean") return value;
  return ["1", "true", "yes", "on"].includes(value.toLowerCase());
};

const numberFromEnv = (value, fallback) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const primaryHost =
  process.env.SMTP_HOST || process.env.EMAIL_HOST || "smtp.gmail.com";
const primaryPort =
  numberFromEnv(process.env.SMTP_PORT, undefined) ||
  numberFromEnv(process.env.EMAIL_PORT, 465);
const primaryUser =
  process.env.SMTP_USER || process.env.EMAIL_USER || process.env.ADMIN_MAIL;
const primaryPass = process.env.SMTP_PASS || process.env.EMAIL_PASS;
const primaryService =
  process.env.SMTP_SERVICE || process.env.EMAIL_SERVICE || undefined;
const smtpSecure =
  typeof process.env.SMTP_SECURE !== "undefined"
    ? booleanFromEnv(process.env.SMTP_SECURE)
    : typeof process.env.EMAIL_SECURE !== "undefined"
    ? booleanFromEnv(process.env.EMAIL_SECURE)
    : primaryPort === 465;
const smtpConnectionUrl =
  process.env.SMTP_URL || process.env.SMTP_CONNECTION_URL || undefined;
const smtpTimeout = numberFromEnv(process.env.SMTP_TIMEOUT_MS, 7000);
const allowEtherealFallback = !booleanFromEnv(
  process.env.DISABLE_ETHEREAL_FALLBACK,
  false
);
const fallbackFrom =
  process.env.SMTP_FROM ||
  process.env.EMAIL_FROM ||
  (primaryUser
    ? `Smart Farmer <${primaryUser}>`
    : "Smart Farmer <no-reply@smartfarmer.dev>");

const hasPrimaryCredentials =
  (primaryHost || primaryService || smtpConnectionUrl) &&
  primaryUser &&
  primaryPass;

let cachedEtherealAccount = null;
let primaryTransportPromise = null;

const sanitizeHost = (value) =>
  typeof value === "string" ? value.replace(/:\/\/.*@/, "://***:***@") : value;

const logTransportConfig = (label, config) => {
  const safeConfig = { ...config };
  if (safeConfig.auth?.user) safeConfig.auth.user = "***";
  if (safeConfig.auth?.pass) safeConfig.auth.pass = "***";
  console.log(`[emailService] ${label}`, safeConfig);
};

const createPrimaryTransport = async () => {
  if (smtpConnectionUrl) {
    const transport = nodemailer.createTransport(smtpConnectionUrl);
    logTransportConfig("Using SMTP connection URL", {
      url: sanitizeHost(smtpConnectionUrl),
    });
    return transport;
  }

  if (!hasPrimaryCredentials) {
    throw new Error(
      "Missing SMTP credentials. Please set SMTP_HOST/PORT/USER/PASS (or SMTP_URL)."
    );
  }

  if (primaryService) {
    const serviceTransport = nodemailer.createTransport({
      service: primaryService,
      auth: {
        user: primaryUser,
        pass: primaryPass,
      },
      pool: booleanFromEnv(process.env.SMTP_POOL, true),
      maxConnections: numberFromEnv(process.env.SMTP_MAX_CONNECTIONS, 3),
      connectionTimeout: smtpTimeout,
      greetingTimeout: smtpTimeout,
      socketTimeout: smtpTimeout,
    });
    logTransportConfig("Using SMTP service transport", {
      service: primaryService,
      pool: serviceTransport.options.pool,
    });
    return serviceTransport;
  }

  const hostTransport = nodemailer.createTransport({
    host: primaryHost,
    port: primaryPort,
    secure: smtpSecure,
    pool: booleanFromEnv(process.env.SMTP_POOL, true),
    maxConnections: numberFromEnv(process.env.SMTP_MAX_CONNECTIONS, 3),
    connectionTimeout: smtpTimeout,
    greetingTimeout: smtpTimeout,
    socketTimeout: smtpTimeout,
    tls: booleanFromEnv(process.env.SMTP_TLS_INSECURE, false)
      ? { rejectUnauthorized: false }
      : undefined,
    auth: {
      user: primaryUser,
      pass: primaryPass,
    },
  });

  logTransportConfig("Using SMTP host transport", {
    host: primaryHost,
    port: primaryPort,
    secure: smtpSecure,
    pool: hostTransport.options.pool,
  });
  return hostTransport;
};

const createEtherealTransport = async () => {
  if (!allowEtherealFallback) {
    throw new Error(
      "Ethereal fallback is disabled and primary transport is unavailable."
    );
  }

  if (!cachedEtherealAccount) {
    cachedEtherealAccount = await nodemailer.createTestAccount();
    console.warn(
      "Using autogenerated Ethereal SMTP credentials for email delivery (development-only)."
    );
    console.warn(`Ethereal user: ${cachedEtherealAccount.user}`);
  }

  return nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false,
    connectionTimeout: smtpTimeout,
    greetingTimeout: smtpTimeout,
    socketTimeout: smtpTimeout,
    auth: {
      user: cachedEtherealAccount.user,
      pass: cachedEtherealAccount.pass,
    },
  });
};

const resetPrimaryTransport = () => {
  primaryTransportPromise = null;
};

const getPrimaryTransport = async () => {
  if (!primaryTransportPromise) {
    primaryTransportPromise = createPrimaryTransport()
      .then(async (transport) => {
        try {
          await transport.verify();
        } catch (verifyError) {
          console.warn(
            "[emailService] SMTP verify failed, transport will be retried per-send.",
            verifyError.code || verifyError.message
          );
        }
        return transport;
      })
      .catch((error) => {
        resetPrimaryTransport();
        throw error;
      });
  }
  return primaryTransportPromise;
};

const isConnectionError = (error) =>
  error &&
  (error.code === "ETIMEDOUT" ||
    error.code === "EAI_AGAIN" ||
    error.code === "ECONNREFUSED" ||
    error.code === "ECONNRESET" ||
    error.code === "ENOTFOUND" ||
    error.command === "CONN");

const sendEmail = async ({ to, subject, html, from }) => {
  try {
    let transport;
    try {
      transport = await getPrimaryTransport();
    } catch (setupError) {
      console.error("[emailService] Unable to init primary transport:", setupError);
      transport = null;
    }

    const resolvedFrom =
      from ||
      (transport?.options?.auth?.user
        ? `Smart Farmer <${transport.options.auth.user}>`
        : fallbackFrom);

    const attemptSend = async (activeTransport, viaFallback = false) => {
      const info = await activeTransport.sendMail({
        from: resolvedFrom,
        to,
        subject,
        html,
      });

      if (activeTransport.options?.host === "smtp.ethereal.email") {
        const previewUrl = nodemailer.getTestMessageUrl(info);
        if (previewUrl) {
          console.warn(
            `Email delivered via Ethereal${viaFallback ? " fallback" : ""}. Preview at:`,
            previewUrl
          );
        }
      }

      return { success: true, fallback: viaFallback };
    };

    if (transport) {
      try {
        return await attemptSend(transport, false);
      } catch (primaryError) {
        if (!isConnectionError(primaryError)) {
          throw primaryError;
        }

        console.warn(
          `[emailService] Primary transport failed (${primaryError.code || primaryError.message}).`
        );
        resetPrimaryTransport();
      }
    }

    const fallbackTransport = await createEtherealTransport();
    return await attemptSend(fallbackTransport, true);
  } catch (error) {
    console.error("Email send error:", error);
    throw error;
  }
};

const sendOtpEmail = async ({ email, otp, name }) => {
  const html = `<p>Hello${name ? ` ${name}` : ""},</p>
    <p>Your OTP for Smart Farmer is: <strong>${otp}</strong></p>
    <p>This code is valid for 10 minutes.</p>`;

  return sendEmail({
    to: email,
    subject: "Your Smart Farmer OTP",
    html,
  });
};

const sendPasswordResetEmail = async ({ email, name, resetUrl }) => {
  const html = `<p>Hello${name ? ` ${name}` : ""},</p>
    <p>Click <a href="${resetUrl}">here</a> to reset your password. This link is valid for 1 hour.</p>`;

  return sendEmail({
    to: email,
    subject: "Reset Your Smart Farmer Password",
    html,
  });
};

module.exports = {
  sendEmail,
  sendOtpEmail,
  sendPasswordResetEmail,
};
